[build]
  command = "cd site && npm run clean && npm run build"
  publish = "site/public"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GATSBY_SUPABASE_ANON_KEY"
  GATSBY_CPU_COUNT = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
